### ISSUE TITLE
ROS settings broken

### ISSUE THREAD

**Issue by timmermansjoy** [Unity-Technologies/Robotics-Nav2-SLAM-Example#36]
When trying to switch the protocol in the ROS settings it gets stuck at recompiling and gives some errors. This project also becomes broken afterwards and have to start it in safe mode idk if this message is for here or the TCP connector itself

![Screenshot 2021-11-09 at 10 04 30 AM](https://user-images.githubusercontent.com/61321383/140894599-43423860-bbac-4f13-b61c-317cc586d3f5.png)

**Comment by mrpropellers** [comment]
Hi @timmermansjoy -- these errors you are seeing are due to differences in the constructor signatures between ROS and ROS2's `Time` messages. This project was built as example integration with the Nav2 stack, specifically, and doesn't support ROS out of the box. If you want to use this project with ROS, you'd need to correct the errors displayed in the console by changing the values passed into the constructors to the appropriate types for ROS. You'll also need to create your own ROS environment with the original navigation package, since the Docker image we provide is for ROS2.

**Comment by Macbull** [comment]
Hello @mrpropellers, I have a working ROS [melodic branch](https://github.com/code-name-57/Robotics-Nav2-SLAM-Example/tree/ros-melodic) of this project in my fork . I have resolved the errors in the script, and have added Dockerfile for ROS melodic with gmapping and turtlebot3.
Its not suitable to be merged with dev or main branch of this repo yet, since Unity project is not hot swappable like you mentioned here https://github.com/Unity-Technologies/Robotics-Nav2-SLAM-Example/issues/22#issuecomment-911970600
Would it make sense to you to create a new branch i.e ros-melodic, where I can target my PR. ? And perhaps, later once the scripts are usable in both ros1 and ros2, this branch could be merged with dev ?

**Comment by mrpropellers** [comment]
Hey @Macbull, glad you figured something out that worked for you! Unfortunately we're not accepting outside contributions for this repo; it's meant to serve as a simple, limited-scope example for users to build off of on their own. If your fork is working well for you, I'd recommend simply continuing your development there. It's unlikely the team at Unity will modify this particular repo much going forward so you are at little risk of getting out of sync.
